---
title: "Intro to DS - Linear Model"
author: ""
date: "today"
# date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    # number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r basic, include=F}
# use this function to conveniently load libraries and work smoothly with knitting
# can add quietly=T option to the require() function
# the loadPkg function essentially replaced/substituted two functions install.packages() and library() in one step.
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }

# unload/detact package when done using it
unloadPkg = function(pkg, character.only = FALSE) { 
  if(!character.only) { pkg <- as.character(substitute(pkg)) } 
  search_item <- paste("package", pkg,sep = ":") 
  while(search_item %in% search()) { detach(search_item, unload = TRUE, character.only = TRUE) } 
}
```

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r xkablesummary}
loadPkg("xtable")
loadPkg("kableExtra")
loadPkg("stringi")
loadPkg("readr")
loadPkg("dplyr")
loadPkg("ggplot2")
loadPkg("countrycode")
loadPkg("reshape")

xkabledply = function(modelsmmrytable, title="Table", digits = 4, pos="left", bso="striped", wide=FALSE) { 
  #' Combining base::summary, xtable, and kableExtra, to easily display model summary. 
  #' wrapper for the base::summary function on model objects
  #' Can also use as head for better display
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param modelsmmrytable This can be a generic table, a model object such as lm(), or the summary of a model object summary(lm()) 
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return HTML table for display
  #' @examples
  #' library("xtable")
  #' library("kableExtra")
  #' xkabledply( df, title="Table testing", pos="left", bso="hover" )
  #' xkabledply( ISLR::Hitters[1:5,] )
  if (wide) { modelsmmrytable <- t(modelsmmrytable) }
  modelsmmrytable %>%
    xtable() %>% 
    kable(caption = title, digits = digits) %>%
    kable_styling(bootstrap_options = bso, full_width = FALSE, position = pos)
}

xkabledplyhead = function(df, rows=5, title="Head", digits = 4, pos="left", bso="striped") { 
  xkabledply(df[1:rows, ], title, digits, pos, bso, wide=FALSE)
}

xkabledplytail = function(df, rows=5, title="Tail", digits = 4, pos="left", bso="striped") { 
  trows = nrow(df)
  xkabledply(df[ (trows-rows+1) : trows, ], title, digits, pos, bso, wide=FALSE)
}

xkablesummary = function(df, title="Table: Statistics summary.", digits = 4, pos="left", bso="striped") { 
  #' Combining base::summary, xtable, and kableExtra, to easily display numeric variable summary of dataframes. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param df The dataframe.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @return The HTML summary table for display, or for knitr to process into other formats 
  #' @examples
  #' xkablesummary( faraway::ozone )
  #' xkablesummary( ISLR::Hitters, title="Five number summary", pos="left", bso="hover"  )
  
  s = summary(df) %>%
    apply( 2, function(x) stringr::str_remove_all(x,c("Min.\\s*:\\s*","1st Qu.\\s*:\\s*","Median\\s*:\\s*","Mean\\s*:\\s*","3rd Qu.\\s*:\\s*","Max.\\s*:\\s*")) ) %>% # replace all leading words
    apply( 2, function(x) stringr::str_trim(x, "right")) # trim trailing spaces left
  
  colnames(s) <- stringr::str_trim(colnames(s))
  
  if ( dim(s)[1] ==6 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max') 
  } else if ( dim(s)[1] ==7 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max','NA') }
  
  xkabledply(s, title=title, digits = digits, pos=pos, bso=bso )
}

xkablevif = function(model, title="VIFs of the model", digits = 3, pos="left", bso="striped", wide=TRUE) { 
  #' Combining faraway::vif, xtable, and kableExtra, to easily display numeric summary of VIFs for a model. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param model The lm or compatible model object.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return The HTML summary table of the VIFs for a model for display, or for knitr to process into other formats 
  #' @examples
  #' xkablevif( lm(Salary~Hits+RBI, data=ISLR::Hitters), wide=T )
  
  vifs = table( names(model$coefficients)[2:length(model$coefficients)] ) # remove intercept to set column names
  vifs[] = faraway::vif(model) # set the values
  if (wide) { vifs <- t(vifs) }
  xkabledply( vifs, title=title, digits = digits, pos=pos, bso=bso )
}
fahr_to_celsius <- function(fahr) {
  celsius <- (fahr - 32) *0.56
  celsius
}
```
### Step 1  
**Import the data**
```{r step01}
global_temps <- data.frame(read_csv("GlobalTemp.csv"))
global_temps$Region <- countrycode(sourcevar = global_temps[, "Country"],origin = "country.name",destination = "continent")
names(global_temps)[1] <- 'Year'
global_temps$Year <- as.integer(format(global_temps$Year, format="%Y"))

```

### Step 2  
**Analyze Global Temperature by regions**
```{r step02}
global_temps <-  na.omit(global_temps)
regional_year_temp_data <-  global_temps %>% group_by(Region, Year) %>% 
summarize(mean(AverageTemperature))
regional_year_temp_data_line_plot = ggplot() + 
  geom_line(data = regional_year_temp_data, aes(x = Year, y = `mean(AverageTemperature)`, group = Region,color=Region)) +
  xlab('Year') +
  ylab('Temperature Level')  +
  geom_point(size = 4, shape = 21)
regional_year_temp_data_qq_plot <- ggplot(regional_year_temp_data, aes(sample = `mean(AverageTemperature)`, colour = Region)) +
  stat_qq() +
  stat_qq_line()
regional_year_temp_data_boxplot <- ggplot(regional_year_temp_data, aes(x=as.factor(regional_year_temp_data$Region), y=`mean(AverageTemperature)`, color=Region)) + 
  geom_boxplot()
regional_year_temp_data_barchart <- ggplot(data=regional_year_temp_data, aes(x=Year, y=`mean(AverageTemperature)`,fill=Region)) +
  geom_bar(stat="identity")

print(regional_year_temp_data_line_plot)
print(regional_year_temp_data_qq_plot)
print(regional_year_temp_data_boxplot)
print(regional_year_temp_data_barchart)

```

### Step 3  
**Analyze the Co2 Emmisions by Regions**
```{r step02}
co2_emissions <- data.frame(read_xls("C02_emissions.xls"))
names(co2_emissions)[1] <- 'Country'
co2_emissions$Region <- countrycode(sourcevar = co2_emissions[, "Country"],origin = "country.name",destination = "continent")
co2_emissions <- data.frame(co2_emissions[ , c(-2,-3,-4)])
co2_emissions <- na.omit(melt(co2_emissions, id=c("Country","Region")))
names(co2_emissions)[3] <- 'Year'
names(co2_emissions)[4] <- 'Emission'
co2_emissions$Year <- as.integer(substring(co2_emissions$Year, 2,5))
co2_emissions$Emission <- as.numeric(format(co2_emissions$Emission, scientific = FALSE))

regional_year_co2_emissions <-  co2_emissions %>% group_by(Region, Year) %>% 
summarize(mean(Emission))

regional_year_co2_emissions_line_plot = ggplot() + 
  geom_line(data = regional_year_co2_emissions, aes(x = Year, y = `mean(Emission)`, group = Region,color=Region)) +
  xlab('Year') +
  ylab('Emissions')  +
  geom_point(size = 4, shape = 21)

regional_year_co2_emissions_qq_plot <- ggplot(regional_year_co2_emissions, aes(sample = `mean(Emission)`, colour = Region)) +
  stat_qq() +
  stat_qq_line()

regional_year_co2_emissions_boxplot <- ggplot(regional_year_co2_emissions, aes(x=as.factor(regional_year_co2_emissions$Region), y=`mean(Emission)`, color=Region)) + 
  geom_boxplot()

regional_year_co2_emissions_barchart <- ggplot(data=regional_year_temp_data, aes(x=Year, y=`mean(AverageTemperature)`,fill=Region)) +
  geom_bar(stat="identity")

print(regional_year_co2_emissions_line_plot)
print(regional_year_co2_emissions_qq_plot)
print(regional_year_co2_emissions_boxplot)
print(regional_year_co2_emissions_barchart)

```