---
title: "Temperature Trends"
author: ""
date: "today"
# date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    # number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r basic, include=F}
# use this function to conveniently load libraries and work smoothly with knitting
# can add quietly=T option to the require() function
# the loadPkg function essentially replaced/substituted two functions install.packages() and library() in one step.
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }

# unload/detact package when done using it
unloadPkg = function(pkg, character.only = FALSE) { 
  if(!character.only) { pkg <- as.character(substitute(pkg)) } 
  search_item <- paste("package", pkg,sep = ":") 
  while(search_item %in% search()) { detach(search_item, unload = TRUE, character.only = TRUE) } 
}
```

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r xkablesummary}
loadPkg("xtable")
loadPkg("kableExtra")
loadPkg("stringi")
loadPkg("readr")
loadPkg("dplyr")
loadPkg("ggplot2")
loadPkg("countrycode")
loadPkg("reshape")
loadPkg("corrplot")
loadPkg("tidyr")
loadPkg("readxl")


xkabledply = function(modelsmmrytable, title="Table", digits = 4, pos="left", bso="striped", wide=FALSE) { 
  #' Combining base::summary, xtable, and kableExtra, to easily display model summary. 
  #' wrapper for the base::summary function on model objects
  #' Can also use as head for better display
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param modelsmmrytable This can be a generic table, a model object such as lm(), or the summary of a model object summary(lm()) 
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return HTML table for display
  #' @examples
  #' library("xtable")
  #' library("kableExtra")
  #' xkabledply( df, title="Table testing", pos="left", bso="hover" )
  #' xkabledply( ISLR::Hitters[1:5,] )
  if (wide) { modelsmmrytable <- t(modelsmmrytable) }
  modelsmmrytable %>%
    xtable() %>% 
    kable(caption = title, digits = digits) %>%
    kable_styling(bootstrap_options = bso, full_width = FALSE, position = pos)
}

xkabledplyhead = function(df, rows=5, title="Head", digits = 4, pos="left", bso="striped") { 
  xkabledply(df[1:rows, ], title, digits, pos, bso, wide=FALSE)
}

xkabledplytail = function(df, rows=5, title="Tail", digits = 4, pos="left", bso="striped") { 
  trows = nrow(df)
  xkabledply(df[ (trows-rows+1) : trows, ], title, digits, pos, bso, wide=FALSE)
}

xkablesummary = function(df, title="Table: Statistics summary.", digits = 4, pos="left", bso="striped") { 
  #' Combining base::summary, xtable, and kableExtra, to easily display numeric variable summary of dataframes. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param df The dataframe.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @return The HTML summary table for display, or for knitr to process into other formats 
  #' @examples
  #' xkablesummary( faraway::ozone )
  #' xkablesummary( ISLR::Hitters, title="Five number summary", pos="left", bso="hover"  )
  
  s = summary(df) %>%
    apply( 2, function(x) stringr::str_remove_all(x,c("Min.\\s*:\\s*","1st Qu.\\s*:\\s*","Median\\s*:\\s*","Mean\\s*:\\s*","3rd Qu.\\s*:\\s*","Max.\\s*:\\s*")) ) %>% # replace all leading words
    apply( 2, function(x) stringr::str_trim(x, "right")) # trim trailing spaces left
  
  colnames(s) <- stringr::str_trim(colnames(s))
  
  if ( dim(s)[1] ==6 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max') 
  } else if ( dim(s)[1] ==7 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max','NA') }
  
  xkabledply(s, title=title, digits = digits, pos=pos, bso=bso )
}

xkablevif = function(model, title="VIFs of the model", digits = 3, pos="left", bso="striped", wide=TRUE) { 
  #' Combining faraway::vif, xtable, and kableExtra, to easily display numeric summary of VIFs for a model. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param model The lm or compatible model object.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return The HTML summary table of the VIFs for a model for display, or for knitr to process into other formats 
  #' @examples
  #' xkablevif( lm(Salary~Hits+RBI, data=ISLR::Hitters), wide=T )
  
  vifs = table( names(model$coefficients)[2:length(model$coefficients)] ) # remove intercept to set column names
  vifs[] = faraway::vif(model) # set the values
  if (wide) { vifs <- t(vifs) }
  xkabledply( vifs, title=title, digits = digits, pos=pos, bso=bso )
}
```

###Step 1
**Import the data**
```{r step1}
global_temps <- data.frame(read_csv("Datasets/GlobalTemp.csv"))
names(global_temps)[1] <- 'Year'
global_temps$Year <- as.integer(format(global_temps$Year, format="%Y"))
global_temps$Decade <- (global_temps$Year - global_temps$Year %% 10)
global_temps$Century <- (global_temps$Year - global_temps$Year %% 100)
global_temps


```

###Step 2
***Analyze global trends by decade and century***
```{r step2}
global_temps <-  na.omit(global_temps)
global_temps$Century <- as.factor(global_temps$Century)

century_temp_data <- global_temps %>% group_by(Century, Year) %>%
  summarize(mean(AverageTemperature))

#line graph of overall trend
century_trends_line_plot <- ggplot() +
  geom_line(data=century_temp_data, aes(x=Year, y=`mean(AverageTemperature)`, color=factor(Century))) +
  xlab("Year") +
  ylab("Average Temperature (celcius)") +
  labs(title="Surface Temperature Trends Over Time", color="Century")
century_trends_line_plot

#boxplot by century
century_year_temp_data_boxplot <- ggplot(century_temp_data, aes(x=as.factor(century_temp_data$Century), y=`mean(AverageTemperature)`, color=Century)) + 
  geom_boxplot() +
  labs(title="Boxplot of Global Surface Temperatures by Century") +
  xlab("Century") +
  ylab("Average Temperature (celcius)") +
  coord_cartesian(ylim = c(0, 20))
century_year_temp_data_boxplot


#boxplot by recent decade
decade_temp_data <- subset(global_temps, Decade >= 1920)
deacde_temp_data <- global_temps %>% group_by(Decade)
decade_year_temp_data_boxplot <- ggplot(decade_temp_data, aes(x=as.factor(decade_temp_data$Decade), y=AverageTemperature, color=Decade)) +
geom_boxplot() +
  labs(title="Boxplot of Global Temperatures in Recent Decades") +
  xlab("Decade") +
  ylab("Average Temperature (celcius)")
decade_year_temp_data_boxplot
  
```

###Step 3
***Hypothesis Tests***
```{r step 3}
#are 1900s and 2000s statistically different?

```

###Step 4
***Data Cleaning for Linear Regression**
```{r step4}
#format dataset to single observation by country per year
summary_temp_data <-  global_temps %>% group_by(Year, Country) %>% 
summarize(mean(AverageTemperature))

#reformat World Bank datasets from wide to long (years 1990-2013)
forest_area <- data.frame(read_xls("Datasets/forest_area.xls"))
forest_area <- subset(forest_area, select = -c(2:34))
forest_area <- subset(forest_area, select = -c(26:32))
colnames(forest_area) <- c("Country", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999",
                           "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010",
                           "2011", "2012", "2013")
forest_area_long <- gather(forest_area, Year, Forest_Area, 2:25, factor_key = TRUE)

renewable_energy_pct <- data.frame(read_xls("Datasets/renewable_energy.xls"))
renewable_energy_pct <- subset(renewable_energy_pct, select = -c(2:34))
renewable_energy_pct <- subset(renewable_energy_pct, select = -c(26:32))
colnames(renewable_energy_pct) <- c("Country", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998",  "1999","2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013")
renewable_energy_pct_long <- gather(renewable_energy_pct, Year, Renew_Energy_Pct, 2:25, factor_key=TRUE)

population <- data.frame(read_xls("Datasets/population.xls"))
population <- subset(population, select = -c(2:34))
population <- subset(population, select = -c(26:32))
colnames(population) <- c("Country", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998",  "1999","2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013")
population_long <- gather(population, Year, Population_Total, 2:25, factor_key=TRUE)

energy_use <- data.frame(read_xls("Datasets/energy_use.xls"))
energy_use <- subset(energy_use, select = -c(2:34))
energy_use <- subset(energy_use, select = -c(26:32))
colnames(energy_use) <- c("Country", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998",  "1999","2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013")
energy_use_long <- gather(energy_use, Year, Energy_Use, 2:25, factor_key=TRUE)

Co2_emissions <- data.frame(read_xls("Datasets/C02_emissions.xls"))
Co2_emissions <- subset(Co2_emissions, select = -c(2:34))
Co2_emissions <- subset(Co2_emissions, select = -c(26:32))
colnames(Co2_emissions) <- c("Country", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998",  "1999","2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013")
co2_emissions_long <- gather(Co2_emissions, Year, Co2_Emissions, 2:25, factor_key = TRUE)

#merge World Bank Data sets
climate_change1 <- merge(forest_area_long, renewable_energy_pct_long, by=c("Country", "Year"))
climate_change2 <- merge(climate_change1, population_long, by=c("Country", "Year"))
climate_change3 <- merge(climate_change2, energy_use_long, by=c("Country", "Year"))
climate_change <- merge(climate_change3, co2_emissions_long, by=c("Country", "Year"))

#merge with temperature data set
summary_temp_data <- subset(summary_temp_data, summary_temp_data$Year >= 1990)
colnames(summary_temp_data) <- c("Year", "Country", "Temperature")

temp_data <- merge(climate_change, summary_temp_data, by=c("Country", "Year"))

```

###Step 5
***Linear Regression***
```{r step5}
#correlation plot
#remove categorical variables for plot
temp_data_cor <- subset(temp_data, select=-c(1,2))
temp_data_cor[is.na(temp_data_cor)] = 0
tempcor <- cor(temp_data_cor)
corrplot(tempcor, method = "number")

#linear model ##Note: Model variables are selected based on varibales closer to 1 and -1
model1 <- lm(Temperature ~ Renew_Energy_Pct + Energy_Use + Co2_Emissions + Forest_Area  + Population_Total, data=temp_data)
summary(model1)
```



