---
title: "Climate Change: Analyzing Earth Surface Temperature Data, Project 2"
author: "Team 3: Sonia Clemens, Salim Haruna, Lauren Korlewitz, and Anna Zhu"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    theme: flatly
    # number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---


```{r basic, include=F}
# use this function to conveniently load libraries and work smoothly with knitting
# can add quietly=T option to the require() function
# the loadPkg function essentially replaced/substituted two functions install.packages() and library() in one step.
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }

# unload/detact package when done using it
unloadPkg = function(pkg, character.only = FALSE) { 
  if(!character.only) { pkg <- as.character(substitute(pkg)) } 
  search_item <- paste("package", pkg,sep = ":") 
  while(search_item %in% search()) { detach(search_item, unload = TRUE, character.only = TRUE) } 
}
```

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r xkablesummary , include=FALSE}
loadPkg("xtable")
loadPkg("kableExtra")
loadPkg("stringi")
loadPkg("readr")
loadPkg("dplyr")
loadPkg("ggplot2")
loadPkg("countrycode")
loadPkg("reshape")
loadPkg("corrplot")
loadPkg("tidyr")
loadPkg("readxl")


xkabledply = function(modelsmmrytable, title="Table", digits = 4, pos="left", bso="striped", wide=FALSE) { 
  #' Combining base::summary, xtable, and kableExtra, to easily display model summary. 
  #' wrapper for the base::summary function on model objects
  #' Can also use as head for better display
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param modelsmmrytable This can be a generic table, a model object such as lm(), or the summary of a model object summary(lm()) 
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return HTML table for display
  #' @examples
  #' library("xtable")
  #' library("kableExtra")
  #' xkabledply( df, title="Table testing", pos="left", bso="hover" )
  #' xkabledply( ISLR::Hitters[1:5,] )
  if (wide) { modelsmmrytable <- t(modelsmmrytable) }
  modelsmmrytable %>%
    xtable() %>% 
    kable(caption = title, digits = digits) %>%
    kable_styling(bootstrap_options = bso, full_width = FALSE, position = pos)
}

xkabledplyhead = function(df, rows=5, title="Head", digits = 4, pos="left", bso="striped") { 
  xkabledply(df[1:rows, ], title, digits, pos, bso, wide=FALSE)
}

xkabledplytail = function(df, rows=5, title="Tail", digits = 4, pos="left", bso="striped") { 
  trows = nrow(df)
  xkabledply(df[ (trows-rows+1) : trows, ], title, digits, pos, bso, wide=FALSE)
}

xkablesummary = function(df, title="Table: Statistics summary.", digits = 4, pos="left", bso="striped") { 
  #' Combining base::summary, xtable, and kableExtra, to easily display numeric variable summary of dataframes. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param df The dataframe.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @return The HTML summary table for display, or for knitr to process into other formats 
  #' @examples
  #' xkablesummary( faraway::ozone )
  #' xkablesummary( ISLR::Hitters, title="Five number summary", pos="left", bso="hover"  )
  
  s = summary(df) %>%
    apply( 2, function(x) stringr::str_remove_all(x,c("Min.\\s*:\\s*","1st Qu.\\s*:\\s*","Median\\s*:\\s*","Mean\\s*:\\s*","3rd Qu.\\s*:\\s*","Max.\\s*:\\s*")) ) %>% # replace all leading words
    apply( 2, function(x) stringr::str_trim(x, "right")) # trim trailing spaces left
  
  colnames(s) <- stringr::str_trim(colnames(s))
  
  if ( dim(s)[1] ==6 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max') 
  } else if ( dim(s)[1] ==7 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max','NA') }
  
  xkabledply(s, title=title, digits = digits, pos=pos, bso=bso )
}

xkablevif = function(model, title="VIFs of the model", digits = 3, pos="left", bso="striped", wide=TRUE) { 
  #' Combining faraway::vif, xtable, and kableExtra, to easily display numeric summary of VIFs for a model. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param model The lm or compatible model object.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return The HTML summary table of the VIFs for a model for display, or for knitr to process into other formats 
  #' @examples
  #' xkablevif( lm(Salary~Hits+RBI, data=ISLR::Hitters), wide=T )
  
  vifs = table( names(model$coefficients)[2:length(model$coefficients)] ) # remove intercept to set column names
  vifs[] = faraway::vif(model) # set the values
  if (wide) { vifs <- t(vifs) }
  xkabledply( vifs, title=title, digits = digits, pos=pos, bso=bso )
}
```

###Global Time Series Analysis
```{r}
#create summary dataset
loadPkg("dplyr")
summary_temps <- global_temps %>% group_by(Year) %>%
  summarize(mean(AverageTemperature))
colnames(summary_temps) <- c("Year","Temperature")

#time series of temperatures from 1743
#ts1 <- ts(data = summary_temps$Temperature, start=c(1743), frequency=1)
# plot.ts(ts1, type="l", col="blue", lwd =2, 
#         ylab="Annual Surface Temperature (Celcius)", xlab="Year") +
#   title("Annual Global Surface Temperatures (1743-2013)") +
#   abline(h=0, col="darkorange2", lwd=2) +
#   text(2000, -0.1, "1743-2013 average")


#subset for data from 1900
summary_temps_1900 <- subset(summary_temps, summary_temps$Year >= 1900)
ts2 <- ts(data = summary_temps_1900$Temperature, start=c(1900), frequency=1)
plot.ts(ts2, type ="l", col="blue", lwd=2,
        ylab="Annual Surface Temperature (Celcius)", xlab="Year") +
  title("Annual Global Surface Temperature (1900-2013)")

loadPkg("forecast")
loadPkg("zoo")
model1 <- auto.arima(as.zoo(ts2))
forecast(model, 40)
plot1 <- plot(forecast(model, 40), main = "Global Temperature Predictions until 2053", xlab = "Year", ylab = "Average Temperature (Celcius)")

```

###United States Analysis
```{r}
US_temps <- subset(global_temps, global_temps$Country == "United States")

summary_US_temps <- US_temps %>% group_by(Year) %>%
  summarize(mean(AverageTemperature))
colnames(summary_US_temps) <- c("Year","Temperature")

US_temps_1900 <- subset(summary_US_temps, summary_US_temps$Year >= 1900)

# ts_us <- ts(data = summary_US_temps$Temperature, start=c(1768), frequency=1)
# ts_us_plot <- plot.ts(ts_us, type ="l", col="blue", lwd=2,
#         ylab="Annual Surface Temperature (Celcius)", xlab="Year") +
#   title("Annual Global Surface Temperature in United States (1768-2013)")

ts_us2 <- ts(data = US_temps_1900$Temperature, start=c(1900), frequency=1)
ts_us_plot2 <- plot.ts(ts_us2, type ="l", col="blue", lwd=2,
        ylab="Annual Surface Temperature (Celcius)", xlab="Year") +
  title("Annual Global Surface Temperature in United States (1900-2013)")


loadPkg("forecast")
loadPkg("zoo")
model2 <- auto.arima(as.zoo(ts_us2))
forecast(model2, 40)
plot2 <- plot(forecast(model2, 40), main = "United States Temperature Predictions until 2053", xlab = "Year", ylab = "Average Temperature (Celcius)")

```

###Iceland Time Series Analysis
```{r}
Iceland_temps <- subset(global_temps, global_temps$Country == "Iceland")

summary_Iceland_temps <- Iceland_temps %>% group_by(Year) %>%
  summarize(mean(AverageTemperature))
colnames(summary_Iceland_temps) <- c("Year","Temperature")

Iceland_temps_1900 <- subset(summary_Iceland_temps, summary_Iceland_temps$Year >= 1900)

ts_ice <- ts(data = Iceland_temps_1900$Temperature, start=c(1900), frequency=1)
ts_ice_plot <- plot.ts(ts_ice, type ="l", col="blue", lwd=2,
        ylab="Annual Surface Temperature (Celcius)", xlab="Year") +
  title("Annual Global Surface Temperature in Iceland (1900-2013)")


loadPkg("forecast")
loadPkg("zoo")
model3 <- auto.arima(as.zoo(ts_ice))
forecast(model3, 40)
plot3 <- plot(forecast(model3, 40), main = "Iceland Temperature Predictions until 2053", xlab = "Year", ylab = "Average Temperature (Celcius)")
```

###Haiti Time Series Analysis
```{r}
Haiti_temps <- subset(global_temps, global_temps$Country == "Haiti")

summary_haiti_temps <- Haiti_temps %>% group_by(Year) %>%
  summarize(mean(AverageTemperature))
colnames(summary_haiti_temps) <- c("Year","Temperature")

haiti_temps_1900 <- subset(summary_haiti_temps, summary_haiti_temps$Year >= 1900)

ts_haiti <- ts(data = haiti_temps_1900$Temperature, start=c(1900), frequency=1)
ts_haiti_plot <- plot.ts(ts_haiti, type ="l", col="blue", lwd=2,
        ylab="Annual Surface Temperature (Celcius)", xlab="Year") +
  title("Annual Global Surface Temperature in Haiti (1900-2013)")


loadPkg("forecast")
loadPkg("zoo")
model4 <- auto.arima(as.zoo(ts_haiti))
forecast(model4, 40)
plot4 <- plot(forecast(model4, 40), main = "Haiti Temperature Predictions until 2053", xlab = "Year", ylab = "Average Temperature (Celcius)")
```




